// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/gpsservice/gpsservice.proto

package go_micro_srv_gpsservice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Gpsservice service

type GpsserviceService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Gpsservice_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Gpsservice_PingPongService, error)
}

type gpsserviceService struct {
	c    client.Client
	name string
}

func NewGpsserviceService(name string, c client.Client) GpsserviceService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.gpsservice"
	}
	return &gpsserviceService{
		c:    c,
		name: name,
	}
}

func (c *gpsserviceService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Gpsservice.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gpsserviceService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Gpsservice_StreamService, error) {
	req := c.c.NewRequest(c.name, "Gpsservice.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &gpsserviceServiceStream{stream}, nil
}

type Gpsservice_StreamService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type gpsserviceServiceStream struct {
	stream client.Stream
}

func (x *gpsserviceServiceStream) Close() error {
	return x.stream.Close()
}

func (x *gpsserviceServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *gpsserviceServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *gpsserviceServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gpsserviceService) PingPong(ctx context.Context, opts ...client.CallOption) (Gpsservice_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Gpsservice.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &gpsserviceServicePingPong{stream}, nil
}

type Gpsservice_PingPongService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type gpsserviceServicePingPong struct {
	stream client.Stream
}

func (x *gpsserviceServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *gpsserviceServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *gpsserviceServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *gpsserviceServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *gpsserviceServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Gpsservice service

type GpsserviceHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Gpsservice_StreamStream) error
	PingPong(context.Context, Gpsservice_PingPongStream) error
}

func RegisterGpsserviceHandler(s server.Server, hdlr GpsserviceHandler, opts ...server.HandlerOption) error {
	type gpsservice interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Gpsservice struct {
		gpsservice
	}
	h := &gpsserviceHandler{hdlr}
	return s.Handle(s.NewHandler(&Gpsservice{h}, opts...))
}

type gpsserviceHandler struct {
	GpsserviceHandler
}

func (h *gpsserviceHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.GpsserviceHandler.Call(ctx, in, out)
}

func (h *gpsserviceHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.GpsserviceHandler.Stream(ctx, m, &gpsserviceStreamStream{stream})
}

type Gpsservice_StreamStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type gpsserviceStreamStream struct {
	stream server.Stream
}

func (x *gpsserviceStreamStream) Close() error {
	return x.stream.Close()
}

func (x *gpsserviceStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *gpsserviceStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *gpsserviceStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *gpsserviceHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.GpsserviceHandler.PingPong(ctx, &gpsservicePingPongStream{stream})
}

type Gpsservice_PingPongStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type gpsservicePingPongStream struct {
	stream server.Stream
}

func (x *gpsservicePingPongStream) Close() error {
	return x.stream.Close()
}

func (x *gpsservicePingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *gpsservicePingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *gpsservicePingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *gpsservicePingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
